language: go
go: ['1.9']
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - go get -v
  - go get -u github.com/jteeuwen/go-bindata/...
  
  - npm run build
notifications:
  email: false