language: go
go: ['1.9']
install: true
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - go get -u github.com/jteeuwen/go-bindata/...
  - go generate -v

  - go get -tv ./...
  - npm run build
notifications:
  email: false